# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15
    - name: Compile code
      run: mvn compile
  test:
    runs-on: ubuntu-latest
    name: Running Unit Tests
    needs: compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15
    - name: Run unit Tests
      run: mvn test
  javadoc:
    runs-on: ubuntu-latest
    name: Generating javadoc
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Generate Javadoc
        run: mvn javadoc:javadoc


  build:

    runs-on: ubuntu-latest
    name: Run mvn build, unit tests and javadoc
    needs: javadoc
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15
    - name: Build with Maven
      run: mvn -B package --file pom.xml